export const symbols = [
  {
    typeName: "常用",
    type: "point",
    content: [
      { name: "综合文化活动中心", iconfont: "&#xe6a9;" },
      { name: "大学", iconfont: "&#xe6aa;" },
      { name: "中学", iconfont: "&#xe6ab;" },
      { name: "小学", iconfont: "&#xe6ad;" },
      { name: "幼儿园", iconfont: "&#xe6ae;" },
      { name: "卫生站", iconfont: "&#xe6af;" },
      { name: "停车场", iconfont: "&#xe6b0;" },
      { name: "菜肉市场", iconfont: "&#xe6b1;" },
      { name: "洗手间", iconfont: "&#xe6b2;" },
      { name: "派出所", iconfont: "&#xe6b3;" },
      { name: "老年活动室", iconfont: "&#xe6b5;" },
      { name: "农家书屋", iconfont: "&#xe6b6;" },
      { name: "垃圾中转站", iconfont: "&#xe6b7;" },
      { name: "健身广场", iconfont: "&#xe6b8;" },
      { name: "户外休闲文体活动广场", iconfont: "&#xe6b9;" },
      { name: "公共服务站", iconfont: "&#xe6ba;" },
      { name: "村委", iconfont: "&#xe6bc;" },
      { name: "祠堂", iconfont: "&#xe6bd;" },
    ],
  },
  {
    typeName: "电力",
    type: "point",
    content: [
      { name: "公用变压器", iconfont: "&#xe69d;" },
      { name: "专用变压器", iconfont: "&#xe69e;" },
      { name: "开闭所", iconfont: "&#xe69f;" },
      { name: "环网柜", iconfont: "&#xe6a0;" },
      { name: "分段断路器", iconfont: "&#xe6a1;" },
      { name: "联络开关", iconfont: "&#xe6a3;" },
      { name: "220kv变电站", iconfont: "&#xe6a4;" },
      { name: "132kv变电站", iconfont: "&#xe6a5;" },
      { name: "110kv变电站", iconfont: "&#xe6a6;" },
      { name: "10kv主线", iconfont: "&#xe6a7;" },
      { name: "10kv支线", iconfont: "&#xe6a8;" },
    ],
  },
  {
    typeName: "城镇",
    type: "point",
    content: [
      { name: "省会城市", iconfont: "&#xe6be;" },
      { name: "副省级市", iconfont: "&#xe6bf;" },
      { name: "直辖市", iconfont: "&#xe6c1;" },
      { name: "县级市", iconfont: "&#xe6c2;" },
      { name: "县城", iconfont: "&#xe6c3;" },
      { name: "地区行署驻地城市", iconfont: "&#xe6c4;" },
      { name: "县", iconfont: "&#xe6c5;" },
      { name: "镇", iconfont: "&#xe6c6;" },
    ],
  },
  {
    typeName: "给排水",
    type: "point",
    content: [{ name: "水库", iconfont: "&#xe6c7;" }],
  },
  {
    typeName: "交通",
    type: "point",
    content: [
      { name: "码头", iconfont: "&#xe6c8;" },
      { name: "机场", iconfont: "&#xe6ca;" },
    ],
  },
  {
    typeName: "电力电信",
    type: "point",
    content: [{ name: "规划能源项目", iconfont: "&#xe6cc;" }],
  },
  {
    typeName: "城乡规划",
    type: "polygon|freePolygon|rect|circle|arrow",
    content: [
      { name: "供热用地", iconfont: "icon-bianzu18" },
      { name: "交通设施用地", iconfont: "icon-bianzu19" },
      { name: "货物流通用地", iconfont: "icon-bianzu20" },
      { name: "加油站", iconfont: "icon-bianzu35" },
      { name: "邮电设施", iconfont: "icon-bianzu107" },
      { name: "雨污水处理用地", iconfont: "icon-bianzu108" },
      { name: "粪便垃圾处理用地", iconfont: "icon-bianzu139" },
      { name: "殡葬设施用地", iconfont: "icon-bianzu140" },
      { name: "消防设施用地", iconfont: "icon-bianzu141" },
      { name: "仓储用地", color: "rgba(163, 127, 255, 0.7)" }, // 色块
      { name: "危险品仓库用地", iconfont: "icon-bianzu142" },
      { name: "铁路用地", iconfont: "icon-bianzu143" },
      { name: "公路用地", iconfont: "icon-bianzu144" },
      { name: "高速公路用地", iconfont: "icon-bianzu145" },
      { name: "长途客运站", iconfont: "icon-bianzu147" },
      { name: "港口用地", iconfont: "icon-bianzu148" },
      { name: "机场用地", iconfont: "rgb(61, 168, 171)" }, //
      { name: "广场用地", iconfont: "icon-bianzu149" },
      { name: "社会停车场用地", iconfont: "icon-bianzu150" },
      { name: "市政公用设施用地", color: "rgb(80, 157, 255)" }, //
      { name: "供电用地", iconfont: "icon-bianzu151" },
      { name: "供水用地", iconfont: "icon-bianzu152" },
      { name: "供燃气用地", iconfont: "icon-bianzu153" },
      { name: "一类居住用地", iconfont: "icon-bianzu154" },
      { name: "二类居住用地", iconfont: "icon-bianzu155" },
      { name: "三类居住用地", iconfont: "icon-bianzu156" },
      { name: "党政机关", iconfont: "icon-bianzu157" },
      { name: "行政办公用地", color: "rgba(244, 0, 0, 0.7)" }, //
      { name: "商业金融用地", iconfont: "icon-bianzu158" },
      { name: "文化娱乐用地", iconfont: "icon-bianzu159" },
      { name: "体育用地", iconfont: "icon-bianzu160" },
      { name: "医疗卫生用地", iconfont: "icon-bianzu161" },
      { name: "教育科研设施", iconfont: "icon-bianzu162" },
      { name: "公共设施", iconfont: "icon-bianzu163" },
      { name: "市场用地", iconfont: "icon-bianzu164" },
      { name: "一类工业用地", iconfont: "icon-bianzu165" },
      { name: "二类工业用地", iconfont: "icon-bianzu166" },
      { name: "三类工业用地", iconfont: "icon-bianzu167" },
      { name: "重要建筑", iconfont: "icon-bianzu168" },
      { name: "公厕", iconfont: "icon-bianzu169" },
      { name: "托儿所", iconfont: "icon-bianzu170" },
      { name: "大型商业设施", iconfont: "icon-bianzu171" },
      { name: "小型商业设施", iconfont: "icon-bianzu173" },
      { name: "储蓄所银行", iconfont: "icon-bianzu174" },
      { name: "社区服务中心", iconfont: "icon-bianzu174" },
      { name: "无障碍通道", iconfont: "icon-bianzu178" },
      { name: "大学", iconfont: "icon-bianzu175" },
      { name: "中学", iconfont: "icon-bianzu176" },
      { name: "小学", iconfont: "icon-bianzu177" },
      { name: "大型服务设施", iconfont: "icon-bianzu178" },
      { name: "小型服务设施", iconfont: "icon-bianzu180" },
      { name: "公安局", iconfont: "icon-bianzu181" },
      { name: "大型金贸设施", iconfont: "icon-bianzu182" },
      { name: "居委会", iconfont: "icon-bianzu183" },
      { name: "农贸市场", iconfont: "icon-bianzu186" }, //
      { name: "垃圾站", iconfont: "icon-bianzu184" },
      { name: "派出所", iconfont: "icon-bianzu185" },
      { name: "青少年活动中心", iconfont: "icon-bianzu187" },
      { name: "物业管理", iconfont: "icon-bianzu188" },
      { name: "社会停车场", iconfont: "icon-bianzu189" },
    ],
  },
  {
    typeName: "规划用途",
    type: "polygon|freePolygon|rect|circle|arrow",
    content: [
      { name: "自然保留地", color: "rgba(180, 180, 180, 0.7)" },
      { name: "园地", color: "rgba(176, 255, 150, 0.7)" },
      { name: "水域", color: "rgba(116, 225, 254, 0.7)" },
      { name: "水工建筑用地", color: "rgba(226, 115, 254, 0.7)" },
      { name: "其他农用地", color: "rgba(65, 255, 211, 0.7)" },
      { name: "农田水利用地", color: "rgba(70, 130, 180, 0.7)" },
      { name: "农村居民点", color: "rgba(244, 140, 139, 0.7)" },
      { name: "农村道路", color: "rgba(250, 155, 49, 0.7)" },
      { name: "林地", color: "rgba(120, 220, 121, 0.7)" },
      { name: "坑塘水面", color: "rgba(116, 225, 254, 0.7)" },
      { name: "交通用地", color: "rgba(250, 155, 49, 0.7)" },
      { name: "基本农田", color: "rgba(250, 255, 49, 0.7)" },
      { name: "耕地", color: "rgba(245, 254, 125, 0.7)" },
      { name: "风景名胜设施用地", color: "rgba(220, 110, 149, 0.7)" },
      { name: "城镇用地", color: "rgba(210, 90, 91, 0.7)" },
      { name: "采矿用地", color: "rgba(209, 160, 120, 0.7)" },
    ],
  },
  {
    typeName: "常用",
    type: "polygon|freePolygon|rect|circle|arrow",
    content: [
      { name: "医疗卫生用地", color: "rgba(210, 93, 114, 0.7)" },
      { name: "文物古迹用地", color: "rgba(211, 110, 85, 0.7)" },
      { name: "文化设施用地", color: "rgba(233, 176, 125, 0.7)" },
      { name: "水域", color: "rgba(115, 177, 156, 0.7)" },
      { name: "商业服务设施用地", color: "rgba(199, 90, 89, 0.7)" },
      { name: "农林用地", color: "rgba(138, 186, 138, 0.7)" },
      { name: "行政办公用地", color: "rgba(149, 87, 140, 0.7)" },
      { name: "共同使用宅基地", color: "rgba(202, 200, 89, 0.7)" },
      { name: "公园绿地", color: "rgba(117, 164, 96, 0.7)" },
      { name: "工业生产设施用地", color: "rgba(121, 77, 70, 0.7)" },
      { name: "服务设施用地", color: "rgba(227, 182, 88, 0.7)" },
      { name: "独立使用宅基地", color: "rgba(147, 143, 88, 0.7)" },
      { name: "地块", color: "rgba(158, 152, 145, 0.7)" },
    ],
  },
  {
    typeName: "农产品",
    type: "polygon|freePolygon|rect|circle|arrow",
    content: [
      { name: "苹果", iconfont: "icon-bianzu190" },
      { name: "柠檬", iconfont: "icon-bianzu191" },
      { name: "葛根", iconfont: "icon-bianzu192" },
      { name: "栗子", iconfont: "icon-bianzu194" },
      { name: "李子", iconfont: "icon-bianzu193" },
      { name: "牛", iconfont: "icon-bianzu196" },
      { name: "清远鸡", iconfont: "icon-bianzu197" },
      { name: "蜜蜂", iconfont: "icon-bianzu195" },
      { name: "柿子", iconfont: "icon-bianzu198" },
      { name: "猪", iconfont: "icon-bianzu199" },
    ],
  },
];
