export const symbols = [
  {
    typeName: "常用",
    type: "point",
    content: [
      { name: "综合文化活动中心", iconfont: "&#xe6a9;" },
      { name: "大学", iconfont: "&#xe6aa;" },
      { name: "中学", iconfont: "&#xe6ab;" },
      { name: "小学", iconfont: "&#xe6ad;" },
      { name: "幼儿园", iconfont: "&#xe6ae;" },
      { name: "卫生站", iconfont: "&#xe6af;" },
      { name: "停车场", iconfont: "&#xe6b0;" },
      { name: "菜肉市场", iconfont: "&#xe6b1;" },
      { name: "洗手间", iconfont: "&#xe6b2;" },
      { name: "派出所", iconfont: "&#xe6b3;" },
      { name: "老年活动室", iconfont: "&#xe6b5;" },
      { name: "农家书屋", iconfont: "&#xe6b6;" },
      { name: "垃圾中转站", iconfont: "&#xe6b7;" },
      { name: "健身广场", iconfont: "&#xe6b8;" },
      { name: "户外休闲文体活动广场", iconfont: "&#xe6b9;" },
      { name: "公共服务站", iconfont: "&#xe6ba;" },
      { name: "村委", iconfont: "&#xe6bc;" },
      { name: "祠堂", iconfont: "&#xe6bd;" },
    ],
  },
  {
    typeName: "电力",
    type: "point",
    content: [
      { name: "公用变压器", iconfont: "&#xe69d;" },
      { name: "专用变压器", iconfont: "&#xe69e;" },
      { name: "开闭所", iconfont: "&#xe69f;" },
      { name: "环网柜", iconfont: "&#xe6a0;" },
      { name: "分段断路器", iconfont: "&#xe6a1;" },
      { name: "联络开关", iconfont: "&#xe6a3;" },
      { name: "220kv变电站", iconfont: "&#xe6a4;" },
      { name: "132kv变电站", iconfont: "&#xe6a5;" },
      { name: "110kv变电站", iconfont: "&#xe6a6;" },
      { name: "10kv主线", iconfont: "&#xe6a7;" },
      { name: "10kv支线", iconfont: "&#xe6a8;" },
    ],
  },
  {
    typeName: "城镇",
    type: "point",
    content: [
      { name: "省会城市", iconfont: "&#xe6be;" },
      { name: "副省级市", iconfont: "&#xe6bf;" },
      { name: "直辖市", iconfont: "&#xe6c1;" },
      { name: "县级市", iconfont: "&#xe6c2;" },
      { name: "县城", iconfont: "&#xe6c3;" },
      { name: "地区行署驻地城市", iconfont: "&#xe6c4;" },
      { name: "县", iconfont: "&#xe6c5;" },
      { name: "镇", iconfont: "&#xe6c6;" },
    ],
  },
  {
    typeName: "给排水",
    type: "point",
    content: [{ name: "水库", iconfont: "&#xe6c7;" }],
  },
  {
    typeName: "交通",
    type: "point",
    content: [
      { name: "码头", iconfont: "&#xe6c8;" },
      { name: "机场", iconfont: "&#xe6ca;" },
    ],
  },
  {
    typeName: "电力电信",
    type: "point",
    content: [{ name: "规划能源项目", iconfont: "&#xe6cc;" }],
  },
  {
    typeName: "城乡规划",
    type: "polygon|freePolygon|rect|circle|arrow",
    content: [
      { name: "供热用地", iconfont: "&#xe6cd;" },
      { name: "交通设施用地", iconfont: "&#xe6eb;" },
      { name: "货物流通用地", iconfont: "&#xe6ec;" },
      { name: "加油站", iconfont: "&#xe6ed;" },
      { name: "邮电设施", iconfont: "&#xe6ef;" },
      { name: "雨污水处理用地", iconfont: "&#xe6f0;" },
      { name: "粪便垃圾处理用地", iconfont: "&#xe6f1;" },
      { name: "殡葬设施用地", iconfont: "&#xe6f2;" },
      { name: "消防设施用地", iconfont: "&#xe6f3;" },
      { name: "仓储用地", iconfont: "&#xe6f4;" },
      { name: "危险品仓库用地", iconfont: "&#xe6f5;" },
      { name: "铁路用地", iconfont: "&#xe6f6;" },
      { name: "公路用地", iconfont: "&#xe6f7;" },
      { name: "高速公路用地", iconfont: "&#xe6f8;" },
      { name: "港口用地", iconfont: "&#xe6f9;" },
      { name: "机场用地", iconfont: "&#xe6fa;" },
      { name: "广场用地", iconfont: "&#xe6fb;" },
      { name: "社会停车场用地", iconfont: "&#xe6fc;" },
      { name: "市政公用设施用地", iconfont: "&#xe6fd;" },
      { name: "供电用地", iconfont: "&#xe6fe;" },
      { name: "供水用地", iconfont: "&#xe6ff;" },
      { name: "供燃气用地", iconfont: "&#xe700;" },
      { name: "居住用地", iconfont: "&#xe701;" },
      { name: "党政机关", iconfont: "&#xe702;" },
      { name: "行政办公用地", iconfont: "&#xe703;" },
      { name: "商业金融用地", iconfont: "&#xe705;" },
      { name: "文化娱乐用地", iconfont: "&#xe706;" },
      { name: "体育用地", iconfont: "&#xe707;" },
      { name: "医疗卫生用地", iconfont: "&#xe708;" },
      { name: "教育科研设施", iconfont: "&#xe70b;" },
      { name: "公共设施", iconfont: "&#xe70c;" },
      { name: "市场用地", iconfont: "&#xe713;" },
      { name: "工业用地", iconfont: "&#xe714;" },
      { name: "重要建筑", iconfont: "&#xe717;" },
      { name: "大型商业设施", iconfont: "&#xe720;" },
      { name: "小型商业设施", iconfont: "&#xe723;" },
      { name: "储蓄所银行", iconfont: "&#xe729;" },
      { name: "社区服务中心", iconfont: "&#xe72d;" },
      { name: "无障碍通道", iconfont: "&#xe72e;" },
      { name: "大型服务设施", iconfont: "&#xe72f;" },
      { name: "小型服务设施", iconfont: "&#xe730;" },
      { name: "公安局", iconfont: "&#xe731;" },
      { name: "大型金贸设施", iconfont: "&#xe732;" },
      { name: "居委会", iconfont: "&#xe733;" },
      { name: "农贸市场", iconfont: "&#xe734;" },
      { name: "青少年活动中心", iconfont: "&#xe735;" },
      { name: "物业管理", iconfont: "&#xe736;" },
      { name: "自然保留地", iconfont: "&#xe737;" },
      { name: "园地", iconfont: "&#xe738;" },
      { name: "水域", iconfont: "&#xe739;" },
      { name: "水工建筑用地", iconfont: "&#xe73a;" },
      { name: "其他农用地", iconfont: "&#xe73b;" },
      { name: "农田水利用地", iconfont: "&#xe73c;" },
      { name: "农村居民点", iconfont: "&#xe73d;" },
      { name: "农村道路", iconfont: "&#xe73e;" },
      { name: "林地", iconfont: "&#xe73f;" },
      { name: "坑塘水面", iconfont: "&#xe740;" },
      { name: "基本农田", iconfont: "&#xe741;" },
      { name: "耕地", iconfont: "&#xe742;" },
      { name: "风景名胜设施", iconfont: "&#xe743;" },
      { name: "城镇用地", iconfont: "&#xe744;" },
      { name: "采矿用地", iconfont: "&#xe745;" },
      { name: "文物古迹用地", iconfont: "&#xe746;" },
      { name: "文化设施用地", iconfont: "&#xe747;" },
      { name: "商业服务设施用地", iconfont: "&#xe748;" },
      { name: "宅基地", iconfont: "&#xe749;" },
      { name: "公园绿地", iconfont: "&#xe74a;" },
      { name: "服务设施用地", iconfont: "&#xe74b;" },
      { name: "地块", iconfont: "&#xe74c;" },
    ],
  },
  {
    typeName: "农业",
    type: "polygon|freePolygon|rect|circle|arrow",
    content: [
      { name: "苹果", iconfont: "&#xe74d;" },
      { name: "柠檬", iconfont: "&#xe74e;" },
      { name: "葛根", iconfont: "&#xe74f;" },
      { name: "栗子", iconfont: "&#xe750;" },
      { name: "李子", iconfont: "&#xe751;" },
      { name: "牛", iconfont: "&#xe752;" },
      { name: "鸡", iconfont: "&#xe753;" },
      { name: "蜜蜂", iconfont: "&#xe754;" },
    ],
  },
];
