const areas = [
  {
    name: "北京",
    code: "110000",
    type: "provincecode",
  },
  {
    name: "广州",
    code: "440100",
    type: "citycode",
  },
  {
    name: "三亚",
    code: "460200",
    type: "citycode",
  },
  {
    name: "上海",
    code: "310000",
    type: "provincecode",
  },
  {
    name: "成都",
    code: "510100",
    type: "citycode",
  },
  {
    name: "深圳",
    code: "440300",
    type: "citycode",
  },
  {
    name: "重庆",
    code: "500000",
    type: "provincecode",
  },
  {
    name: "杭州",
    code: "330100",
    type: "citycode",
  },
  {
    name: "西安",
    code: "610100",
    type: "citycode",
  },
  {
    name: "长沙",
    code: "430100",
    type: "citycode",
  },
  {
    name: "南京",
    code: "320100",
    type: "citycode",
  },
  {
    name: "昆明",
    code: "530100",
    type: "citycode",
  },
  {
    name: "厦门",
    code: "350200",
    type: "citycode",
  },
  {
    name: "海口",
    code: "460100",
    type: "citycode",
  },
  {
    name: "武汉",
    code: "420100",
    type: "citycode",
  },
  {
    name: "哈尔滨",
    code: "230100",
    type: "citycode",
  },
  {
    name: "苏州",
    code: "320500",
    type: "citycode",
  },
  {
    name: "珠海",
    code: "440400",
    type: "citycode",
  },
  {
    name: "郑州",
    code: "410100",
    type: "citycode",
  },
  {
    name: "惠州",
    code: "441300",
    type: "citycode",
  },
];
const stars = [
  { name: "五星级", key: "5star" },
  { name: "四星级", key: "4star" },
  { name: "三星级", key: "3star" },
  { name: "经济型", key: "0star" },
];
const brand = [
  { name: "亚朵", key: "亚朵" },
  { name: "希尔顿", key: "希尔顿" },
  { name: "柏锐", key: "柏锐" },
  { name: "万丽", key: "万丽" },
  { name: "维景国际", key: "维景国际" },
  { name: "喜来登", key: "喜来登" },
  { name: "丽思卡尔顿", key: "丽思卡尔顿" },
  { name: "香格里拉", key: "香格里拉" },
  { name: "君澜度假", key: "君澜度假" },
  { name: "万豪铂尔曼", key: "万豪铂尔曼" },
  { name: "美高梅", key: "美高梅" },
  { name: "康莱德", key: "康莱德" },
  { name: "湘投阳光", key: "湘投阳光" },
  { name: "艾迪逊", key: "艾迪逊" },
  { name: "皇冠假日", key: "皇冠假日" },
  { name: "索菲特", key: "索菲特" },
  { name: "豪生", key: "豪生" },
  { name: "威斯汀", key: "威斯汀" },
  { name: "君悦", key: "君悦" },
  { name: "瑰丽", key: "瑰丽" },
  { name: "莱佛士", key: "莱佛士" },
  { name: "瑞吉", key: "瑞吉" },
  { name: "JW万豪", key: "JW万豪" },
  { name: "悦榕庄", key: "悦榕庄" },
  { name: "铂瑞酒店", key: "铂瑞酒店" },
  { name: "洲际", key: "洲际" },
  { name: "温德姆", key: "温德姆" },
  { name: "文华东方", key: "文华东方" },
  { name: "维也纳", key: "维也纳" },
  { name: "皇庭假日", key: "皇庭假日" },
  { name: "Clubmed", key: "Clubmed" },
];
export { areas, stars, brand };
