const config = [
  {
    id: "8c10c3904b5d445ab6eea755cffa2c7cgegen",
    is_deleted: "0",
    main_id: "9f9bc44de1884bedbfb59fe8440edceb",
    name: "葛根",
    value1: "img/mark/gegen.png",
    value2: "农产品",
    value3: "icon",
  },
  {
    id: "8c10c3904b5d445ab6eea755cffa2c7clizhi",
    is_deleted: "0",
    main_id: "9f9bc44de1884bedbfb59fe8440edceb",
    name: "李子",
    value1: "img/mark/lizhi.png",
    value2: "农产品",
    value3: "icon",
  },
  {
    id: "8c10c3904b5d445ab6eea755cffa2c7clizzi",
    is_deleted: "0",
    main_id: "9f9bc44de1884bedbfb59fe8440edceb",
    name: "栗子",
    value1: "img/mark/lizzi.png",
    value2: "农产品",
    value3: "icon",
  },
  {
    id: "8c10c3904b5d445ab6eea755cffa2c7cmifeng",
    is_deleted: "0",
    main_id: "9f9bc44de1884bedbfb59fe8440edceb",
    name: "蜜蜂",
    value1: "img/mark/mifeng.png",
    value2: "农产品",
    value3: "icon",
  },
  {
    id: "8c10c3904b5d445ab6eea755cffa2c7cniu",
    is_deleted: "0",
    main_id: "9f9bc44de1884bedbfb59fe8440edceb",
    name: "牛",
    value1: "img/mark/niu.png",
    value2: "农产品",
    value3: "icon",
  },
  {
    id: "8c10c3904b5d445ab6eea755cffa2c7cqingyuanji",
    is_deleted: "0",
    main_id: "9f9bc44de1884bedbfb59fe8440edceb",
    name: "清远鸡",
    value1: "img/mark/qingyuanji.png",
    value2: "农产品",
    value3: "icon",
  },
  {
    id: "8c10c3904b5d445ab6eea755cffa2c7cshizi",
    is_deleted: "0",
    main_id: "9f9bc44de1884bedbfb59fe8440edceb",
    name: "柿子",
    value1: "img/mark/shizi.png",
    value2: "农产品",
    value3: "icon",
  },
  {
    id: "8c10c3904b5d445ab6eea755cffa2c7czhu",
    is_deleted: "0",
    main_id: "9f9bc44de1884bedbfb59fe8440edceb",
    name: "猪",
    value1: "img/mark/zhu.png",
    value2: "农产品",
    value3: "icon",
  },
];

// 城市规划
const planConf = {
  type: "城市规划领域",
  items: [
    {
      id: "供热用地",
      name: "供热用地",
      sigle: true,
      value1: "rgba(0,95,127,0.7)",
      value2: "城市规划",
      value3: "icon",
      value4: "img/symbolstore/gongreyongdi.svg",
    },
    {
      id: "交通设施用地",
      name: "交通设施用地",
      sigle: true,
      value1: "rgba(0,95,127,0.7)",
      value2: "城市规划",
      value3: "icon",
      value4: "img/symbolstore/jiaotongsheshiyongdi.svg",
    },
    {
      id: "货物流通用地",
      name: "货物流通用地",
      sigle: true,
      value1: "rgba(0,95,127,0.7)",
      value2: "城市规划",
      value3: "icon",
      value4: "img/symbolstore/huowuliutongyongdi.svg",
    },
    {
      id: "加油站",
      name: "加油站",
      sigle: true,
      value1: "rgba(0,95,127,0.7)",
      value2: "城市规划",
      value3: "icon",
      value4: "img/symbolstore/jiayouzhan.svg",
    },
    {
      id: "邮电设施用地",
      name: "邮电设施用地",
      sigle: true,
      value1: "rgba(0,95,127,0.7)",
      value2: "城市规划",
      value3: "icon",
      value4: "img/symbolstore/youdiansheshiyongdi.svg",
    },
    {
      id: "雨污水处理用地",
      name: "雨污水处理用地",
      sigle: true,
      value1: "rgba(0,95,127,0.7)",
      value2: "城市规划",
      value3: "icon",
      value4: "img/symbolstore/yuwushuichuliyongdi.svg",
    },
    {
      id: "粪便垃圾处理用地",
      name: "粪便垃圾处理用地",
      sigle: true,
      value1: "rgba(0,95,127,0.7)",
      value2: "城市规划",
      value3: "icon",
      value4: "img/symbolstore/fenbianlajichuliyongdi.svg",
    },
    {
      id: "殡葬设施用地",
      name: "殡葬设施用地",
      sigle: true,
      value1: "rgba(0,95,127,0.7)",
      value2: "城市规划",
      value3: "icon",
      value4: "img/symbolstore/binzangsheshiyongdi.svg",
    },
    {
      id: "消防设施用地",
      name: "消防设施用地",
      sigle: true,
      value1: "rgba(0,95,127,0.7)",
      value2: "城市规划",
      value3: "icon",
      value4: "img/symbolstore/xiaofangsheshiyongdi.svg",
    },
    {
      id: "仓储用地",
      name: "仓储用地",
      value1: "rgba(163,127,255,0.7)",
      value2: "城市规划",
      value3: "",
    },
    {
      id: "危险品仓库用地",
      name: "危险品仓库用地",
      sigle: true,
      value1: "rgba(163,127,255,0.7)",
      value2: "城市规划",
      value3: "icon",
      value4: "img/symbolstore/weixianpincangkuyongdi.svg",
    },
    {
      id: "对外交通用地",
      name: "对外交通用地",
      value1: "rgba(61, 168, 171, 1)",
      value2: "城市规划",
      value3: "",
    },
    {
      id: "铁路用地",
      name: "铁路用地",
      sigle: true,
      value1: "rgba(163,127,255,0.7)",
      value2: "城市规划",
      value3: "icon",
      value4: "img/symbolstore/tieluyongdi.svg",
    },
    {
      id: "公路用地",
      name: "公路用地",
      sigle: true,
      value1: "rgba(163,127,255,0.7)",
      value2: "城市规划",
      value3: "icon",
      value4: "img/symbolstore/gongluyongdi.svg",
    },
    {
      id: "高速公路用地",
      name: "高速公路用地",
      sigle: true,
      value1: "rgba(163,127,255,0.7)",
      value2: "城市规划",
      value3: "icon",
      value4: "img/symbolstore/gaosugongluyongdi.svg",
    },
    {
      id: "长途客运站用地",
      name: "长途客运站用地",
      sigle: true,
      value1: "rgba(61,168,171,0.7)",
      value2: "城市规划",
      value3: "icon",
      value4: "img/symbolstore/changtukeyunzhanyongdi.svg",
    },
    {
      id: "港口用地",
      name: "港口用地",
      sigle: true,
      value1: "rgba(61,168,171,0.7)",
      value2: "城市规划",
      value3: "icon",
      value4: "img/symbolstore/gangkouyongdi.svg",
    },
    {
      id: "机场用地",
      name: "机场用地",
      value1: "rgba(61,168,171,1)",
      value2: "城市规划",
      value3: "rgba(61,168,171,1)",
    },
    {
      id: "公路",
      name: "公路",
      value1: "img/symbolstore/gonglu.svg",
      value2: "城市规划",
      value3: "rgba(61,168,171,1)",
    },
    {
      id: "广场用地",
      name: "广场用地",
      sigle: true,
      value1: "rgba(61,168,171,0.7)",
      value2: "城市规划",
      value3: "icon",
      value4: "img/symbolstore/guangchangyongdi.svg",
    },
    {
      id: "社会停车场用地",
      name: "社会停车场用地",
      sigle: true,
      value1: "rgba(61,168,171,0.7)",
      value2: "城市规划",
      value3: "icon",
      value4: "img/symbolstore/guangchangyongdi.svg",
    },
    {
      id: "市政共用设施用地",
      name: "市政共用设施用地",
      value1: "rgba(80,157,255)",
      value2: "城市规划",
      value3: "rgba(80,157,255)",
    },
    {
      id: "供电用地",
      name: "供电用地",
      sigle: true,
      value1: "rgba(80,157,255)",
      value2: "城市规划",
      value3: "icon",
      value4: "img/symbolstore/gongdianyongdi.svg",
    },
    {
      id: "供水用地",
      name: "供水用地",
      sigle: true,
      value1: "rgba(80,157,255)",
      value2: "城市规划",
      value3: "icon",
      value4: "img/symbolstore/gongshuiyongdi.svg",
    },
    {
      id: "供燃气用地",
      name: "供燃气用地",
      sigle: true,
      value1: "rgba(80,157,255)",
      value2: "城市规划",
      value3: "icon",
      value4: "img/symbolstore/gongranqiyongdi.svg",
    },
    {
      id: "一类居住用地",
      name: "一类居住用地",
      value1: "rgba(254,255,118)",
      value2: "城市规划",
      value3: "rgba(254,255,118)",
    },
    {
      id: "二类居住用地",
      name: "二类居住用地",
      value1: "rgba(254,254,0)",
      value2: "城市规划",
      value3: "rgba(254,254,0)",
    },
    {
      id: "三类居住用地",
      name: "三类居住用地",
      value1: "rgba(251,223,120)",
      value2: "城市规划",
      value3: "rgba(251,223,120)",
    },
    {
      id: "党政机关",
      name: "党政机关",
      sigle: true,
      value1: "rgba(244,0,0, 0.7)",
      value2: "城市规划",
      value3: "icon",
      value4: "img/symbolstore/dangzhengjiguan.svg",
    },
    {
      id: "行政办公用地",
      name: "行政办公用地",
      value1: "rgba(244,0,0, 0.7)",
      value2: "城市规划",
      value3: "rgba(244,0,0, 0.7)",
    },
    {
      id: "商业金融用地",
      name: "商业金融用地",
      value1: "rgba(240,0,0, 0.7)",
      value2: "城市规划",
      value3: "rgba(240,0,0, 0.7)",
    },
    {
      id: "文化娱乐用地",
      name: "文化娱乐用地",
      value1: "rgba(248,158,124, 0.7)",
      value2: "城市规划",
      value3: "rgba(248,158,124, 0.7)",
    },
    {
      id: "体育用地",
      name: "体育用地",
      sigle: true,
      value1: "rgba(106,171,1, 0.7)",
      value2: "城市规划",
      value3: "icon",
      value4: "img/symbolstore/tiyuyongdi.svg",
    },
    {
      id: "医疗卫生用地",
      name: "医疗卫生用地",
      sigle: true,
      value1: "rgba(240,0,0, 0.7)",
      value2: "城市规划",
      value3: "icon",
      value4: "img/symbolstore/yiliaoweishengyongdi.svg",
    },
    {
      id: "教育科研设计用地",
      name: "教育科研设计用地",
      value1: "rgba(248,155,185, 0.7)",
      value2: "城市规划",
      value3: "rgba(248,155,185, 0.7)",
    },
    {
      id: "其他公共设施用地",
      name: "其他公共设施用地",
      value1: "rgba(248,155,185, 0.7)",
      value2: "城市规划",
      value3: "rgba(248,155,185, 0.7)",
    },
    {
      id: "市场用地",
      name: "市场用地",
      sigle: true,
      value1: "rgba(244,0,0, 0.7)",
      value2: "城市规划",
      value3: "icon",
      value4: "img/symbolstore/shichangyongdi.svg",
    },
    {
      id: "一类工业用地",
      name: "一类工业用地",
      value1: "rgba(216,175,128,0.7)",
      value2: "城市规划",
      value3: "rgba(216,175,128,0.7)",
    },
    {
      id: "二类工业用地",
      name: "二类工业用地",
      value1: "rgba(182,127,93,0.7)",
      value2: "城市规划",
      value3: "rgba(182,127,93,0.7)",
    },
    {
      id: "三类工业用地",
      name: "三类工业用地",
      value1: "rgba(134,92,65,0.7)",
      value2: "城市规划",
      value3: "rgba(134,92,65,0.7)",
    },
    {
      id: "重要建筑",
      name: "重要建筑",
      sigle: true,
      value1: "rgba(255,255,255, 0.7)",
      value2: "城市规划",
      value3: "icon",
      value4: "img/symbolstore/zhongyaojianzhu.svg",
    },
    {
      id: "公厕",
      name: "公厕",
      sigle: true,
      value1: "rgba(255,255,255, 0.7)",
      value2: "城市规划",
      value3: "icon",
      value4: "img/symbolstore/gongce.svg",
    },
    {
      id: "托儿所",
      name: "托儿所",
      sigle: true,
      value1: "rgba(255,255,255, 0.7)",
      value2: "城市规划",
      value3: "icon",
      value4: "img/symbolstore/tuoersuo.svg",
    },
    {
      id: "大型商业设施",
      name: "大型商业设施",
      sigle: true,
      value1: "rgba(255,255,255, 0.7)",
      value2: "城市规划",
      value3: "icon",
      value4: "img/symbolstore/daxingshangyesheshi.svg",
    },
    {
      id: "大型商业设施",
      name: "大型商业设施",
      sigle: true,
      value1: "rgba(255,255,255, 0.7)",
      value2: "城市规划",
      value3: "icon",
      value4: "img/symbolstore/daxingshangyesheshi.svg",
    },
    {
      id: "小型商业设施",
      name: "小型商业设施",
      sigle: true,
      value1: "rgba(255,255,255, 0.7)",
      value2: "城市规划",
      value3: "icon",
      value4: "img/symbolstore/xiaoxingshangyesheshi.svg",
    },
    {
      id: "储蓄所(银行)",
      name: "储蓄所(银行)",
      sigle: true,
      value1: "rgba(255,255,255, 0.7)",
      value2: "城市规划",
      value3: "icon",
      value4: "img/symbolstore/chuxusuo(yinhang).svg",
    },
    {
      id: "社区服务中心",
      name: "社区服务中心",
      sigle: true,
      value1: "rgba(255,255,255, 0.7)",
      value2: "城市规划",
      value3: "icon",
      value4: "img/symbolstore/shequfuwuzhongxin.svg",
    },
    {
      id: "中学",
      name: "中学",
      sigle: true,
      value1: "rgba(255,255,255, 0.7)",
      value2: "城市规划",
      value3: "icon",
      value4: "img/symbolstore/zhongxue.svg",
    },
    {
      id: "小学",
      name: "小学",
      sigle: true,
      value1: "rgba(255,255,255, 0.7)",
      value2: "城市规划",
      value3: "icon",
      value4: "img/symbolstore/xiaoxue.svg",
    },
    {
      id: "大学",
      name: "大学",
      sigle: true,
      value1: "rgba(255,255,255, 0.7)",
      value2: "城市规划",
      value3: "icon",
      value4: "img/symbolstore/daxue.svg",
    },
    {
      id: "无障碍通道",
      name: "无障碍通道",
      sigle: true,
      value1: "rgba(255,255,255, 0.7)",
      value2: "城市规划",
      value3: "icon",
      value4: "img/symbolstore/wuzhangaitongdao.svg",
    },
    {
      id: "大型服务设施",
      name: "大型服务设施",
      sigle: true,
      value1: "rgba(255,255,255, 0.7)",
      value2: "城市规划",
      value3: "icon",
      value4: "img/symbolstore/daxingfuwusheshi.svg",
    },
    {
      id: "小型服务设施",
      name: "小型服务设施",
      sigle: true,
      value1: "rgba(255,255,255, 0.7)",
      value2: "城市规划",
      value3: "icon",
      value4: "img/symbolstore/xiaoxingfuwusheshi.svg",
    },
    {
      id: "文化站",
      name: "文化站",
      sigle: true,
      value1: "rgba(255,255,255, 0.7)",
      value2: "城市规划",
      value3: "icon",
      value4: "img/symbolstore/wenhuazhan.svg",
    },
    {
      id: "公安局",
      name: "公安局",
      sigle: true,
      value1: "rgba(255,255,255, 0.7)",
      value2: "城市规划",
      value3: "icon",
      value4: "img/symbolstore/gonganju.svg",
    },
    {
      id: "大型金贸设施",
      name: "大型金贸设施",
      sigle: true,
      value1: "rgba(255,255,255, 0.7)",
      value2: "城市规划",
      value3: "icon",
      value4: "img/symbolstore/daxingjinmaosheshi.svg",
    },
    {
      id: "居民委员会",
      name: "居民委员会",
      sigle: true,
      value1: "rgba(255,255,255, 0.7)",
      value2: "城市规划",
      value3: "icon",
      value4: "img/symbolstore/juminweiyuanhui.svg",
    },
    {
      id: "垃圾站",
      name: "垃圾站",
      sigle: true,
      value1: "rgba(255,255,255, 0.7)",
      value2: "城市规划",
      value3: "icon",
      value4: "img/symbolstore/lajizhan.svg",
    },
    {
      id: "派出所",
      name: "派出所",
      sigle: true,
      value1: "rgba(255,255,255, 0.7)",
      value2: "城市规划",
      value3: "icon",
      value4: "img/symbolstore/paichusuo.svg",
    },
    {
      id: "农贸市场",
      name: "农贸市场",
      sigle: true,
      value1: "rgba(255,255,255, 0.7)",
      value2: "城市规划",
      value3: "icon",
      value4: "img/symbolstore/nongmaoshichang.svg",
    },
    {
      id: "青少年活动中心",
      name: "青少年活动中心",
      sigle: true,
      value1: "rgba(255,255,255, 0.7)",
      value2: "城市规划",
      value3: "icon",
      value4: "img/symbolstore/qingshaonianhuodongzhongxin.svg",
    },
    {
      id: "物业管理",
      name: "物业管理",
      sigle: true,
      value1: "rgba(255,255,255, 0.7)",
      value2: "城市规划",
      value3: "icon",
      value4: "img/symbolstore/wuyeguanli.svg",
    },
    {
      id: "社会停车场用地",
      name: "社会停车场用地",
      sigle: true,
      value1: "rgba(255,255,255, 0.7)",
      value2: "城市规划",
      value3: "icon",
      value4: "img/symbolstore/shehuitingchechagyongdi.svg",
    },
  ],
};

// 电力
const electricPowerConf = {
  type: "电力行业",
  items: [
    {
      id: "公用变压器",
      name: "公用变压器",
      value1: "img/symbolstore/gongyongbianyaqi.svg",
      value2: "电力",
      value3: "icon",
    },
    {
      id: "专用变压器",
      name: "专用变压器",
      value1: "img/symbolstore/zhuanyongbianyaqi.svg",
      value2: "电力",
      value3: "icon",
    },
    {
      id: "箱式公用变压器",
      name: "箱式公用变压器",
      value1: "img/symbolstore/xiangshigongyongbianyaqi.svg",
      value2: "电力",
      value3: "icon",
    },
    {
      id: "箱式专用变压器",
      name: "箱式专用变压器",
      value1: "img/symbolstore/xiangshizhuanyongbianyaqi.svg",
      value2: "电力",
      value3: "icon",
    },
    {
      id: "开闭所",
      name: "开闭所",
      value1: "img/symbolstore/kaibisuo.svg",
      value2: "电力",
      value3: "icon",
    },
    {
      id: "环网柜",
      name: "环网柜",
      value1: "img/symbolstore/huanwanggui.svg",
      value2: "电力",
      value3: "icon",
    },
    {
      id: "分段断路器",
      name: "分段断路器",
      value1: "img/symbolstore/fenduanduanluqi.svg",
      value2: "电力",
      value3: "icon",
    },
    {
      id: "联络开关",
      name: "联络开关",
      value1: "img/symbolstore/lianluokaiguan.svg",
      value2: "电力",
      value3: "icon",
    },
    {
      id: "隔离开关",
      name: "隔离开关",
      value1: "img/symbolstore/gelikaiguan.svg",
      value2: "电力",
      value3: "icon",
    },
    {
      id: "220kV变电站",
      name: "220kV变电站",
      value1: "img/symbolstore/220kVbiandianzhan.svg",
      value2: "电力",
      value3: "icon",
    },
    {
      id: "132kV变电站",
      name: "132kV变电站",
      value1: "img/symbolstore/132kVbiandianzhan.svg",
      value2: "电力",
      value3: "icon",
    },
    {
      id: "110kV变电站",
      name: "110kV变电站",
      value1: "img/symbolstore/110kVbiandianzhan.svg",
      value2: "电力",
      value3: "icon",
    },
    {
      id: "10kV主线",
      name: "10kV主线",
      value1: "img/symbolstore/10kVzhuxian.svg",
      value2: "电力",
      value3: "icon",
    },
    {
      id: "10kV支线",
      name: "10kV支线",
      value1: "img/symbolstore/10kVzhixian.svg",
      value2: "电力",
      value3: "icon",
    },
  ],
};

export { config, planConf, electricPowerConf };
